### PR TITLE
exp-if allowing to call method

### PR DESCRIPTION
**Pull request by lukasotocerny**
In `exp-if` attribute allowing to have methods which are called and return a boolean, subject to which an element is shown or not.

### CODE REVIEW

**Comment by hackal** [comment]
Think about this case:

https://gist.github.com/hackal/80614304d02331ce269878e2c171607f

`seen` method has a dependency in the model `seenVar`. `toggleSeen` method changes the `seenVar` dependency. At the moment the `seen` method evaluates only during bind, works well, but I suggest it should evaluate every time something in model changes. 

See Vue.js example:

https://jsfiddle.net/50wL7mdz/335526/

**Comment by lukasotocerny** [comment]
@hackal I think that is unnecessary overhead and overkill for now. Although I will add comment to Docs specifying that it's called only once at the beginning. Your suggestion is kind of related to Virtual DOM (if you want to do it in an efficient way), so perhaps v2.0

**Comment by hackal** [comment]
I disagree, the current implementation is no different then using just variable set at the beginning. I will merge this PR and implement the other feature.

**Comment by lukasotocerny** [comment]
@hackal It IS different than just setting a variable at the beginning. You can have custom code associated with situations where something is or isn't displayed.

Ok, lets see what you come up with.

**Pull request merged**
